# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# データファイルの定義
a = Analysis(
    ['direct_launcher.py'],
    pathex=['../src'],
    binaries=[],
    datas=[
        ('../assets', 'assets'),
        ('../src/attendance_app/templates', 'templates'), 
        ('../settings.json', '.'),
        ('../service_account.json.template', '.'),
        ('../src', 'src'),
    ],
    hiddenimports=[
        'attendance_app',
        'attendance_app.config',
        'attendance_app.main',
        'attendance_app.settings',
        'attendance_app.path_manager',
        'attendance_app.spreadsheet',
        'attendance_app.main_printer',
        'attendance_app.report_screen',
        'attendance_app.student_registry_screen',
        'attendance_app.printer_control',
        'attendance_app.drive_handler',
        'attendance_app.offline_storage',
        'attendance_app.notification_monitor',
        'attendance_app.student_data_manager',
        'attendance_app.report_system',
        'attendance_app.report_system.data_analyzer',
        'attendance_app.report_system.excel_report_generator',
        'attendance_app.report_system.utils',
        'kivy.deps.angle',
        'kivy.deps.glew', 
        'kivy.deps.sdl2',
        'kivy.core.window',
        'kivy.core.audio',
        'kivy.core.camera',
        'kivy.core.image',
        'kivy.core.spelling',
        'kivy.core.text',
        'kivy.core.video',
        'kivy.uix.boxlayout',
        'kivy.uix.button',
        'kivy.uix.label',
        'kivy.uix.popup',
        'kivy.uix.screenmanager',
        'kivy.uix.scrollview',
        'kivy.uix.textinput',
        'kivy.uix.spinner',
        'kivy.uix.gridlayout',
        'kivy.uix.image',
        'kivy.uix.togglebutton',
        'kivy.clock',
        'kivy.graphics',
        'kivy.core.text',
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.drawing',
        'openpyxl.worksheet',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'google.auth',
        'google.auth.transport.requests',
        'google.oauth2.credentials',
        'google.oauth2.service_account',
        'googleapiclient',
        'googleapiclient.discovery',
        'gspread',
        'webbrowser',
        'threading',
        'pathlib',
        'datetime',
        'csv',
        'json',
        'tempfile',
        'base64',
        'io',
        'os',
        'sys',
        'subprocess',
        'pydantic',
        'pydantic_settings',
        'dotenv',
        'pandas',
        'numpy'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'IPython',
        'jupyter',
        'notebook'
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AttendanceManagementSystem',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AttendanceManagementSystem',
)